#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images from templates.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker build \
            --build-arg "ALPINE_VERSION=${ALPINE_VERSION}" \
            --build-arg "TERRAFORM_VERSION=${TERRAFORM_VERSION}" \
            --build-arg "TFLINT_VERSION=${TFLINT_VERSION}" \
            --tag "ghcr.io/foreflight/terraform:${TERRAFORM_VERSION}" .

        ./scripts/test

        docker images
    fi
fi
