#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Test container images built from templates.
"
}

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    if [[ "${1:-}" == "--help" ]]; then
        usage
    else
        docker \
            run --rm \
            "ghcr.io/foreflight/terraform:${TERRAFORM_VERSION}" -version

        docker \
            run --rm --entrypoint \
            tflint "ghcr.io/foreflight/terraform:${TERRAFORM_VERSION}" --version

        docker \
            run --rm --entrypoint \
            aws "ghcr.io/foreflight/terraform:${TERRAFORM_VERSION}" --version

        # Running "aws help" invokes some other features in the AWS CLI which
        # has other dependencies like "groff."
        docker \
            run --rm --entrypoint \
            aws "ghcr.io/foreflight/terraform:${TERRAFORM_VERSION}" help
    fi
fi
