name: Build and Publish ForeFlight Terraform Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build v. ${{ matrix.terraform_version }} image on ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        terraform_version: ["1.12.2", "1.10.5"]
        include:
          - terragrunt_version: "v0.83.2"
          - tflint_version: "v0.58.1"
          - alpine_version: "3.22"
    env:
      TERRAFORM_VERSION: ${{ matrix.terraform_version }}
      TERRAGRUNT_VERSION: ${{ matrix.terragrunt_version }}
      TFLINT_VERSION: ${{ matrix.tflint_version }}
      ALPINE_VERSION: ${{ matrix.alpine_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Execute cibuild
        run: ./scripts/cibuild

      - name: Execute cipublish
        run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          CR_USER: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  combine-images:
    name: Combine v. ${{ matrix.terraform_version }} images into multi-arch image
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.12.2", "1.10.5"]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifest for ${{ matrix.terraform_version }}
        run: |
          docker manifest create ghcr.io/foreflight/terraform:${{ matrix.terraform_version }}  \
            ghcr.io/foreflight/terraform:${{ matrix.terraform_version }}-aarch64 \
            ghcr.io/foreflight/terraform:${{ matrix.terraform_version }}-x86_64
            
          docker manifest push ghcr.io/foreflight/terraform:${{ matrix.terraform_version }}