name: Build and Publish ForeFlight Terraform Image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.12.2"]
        include:
          - alpine_version: "3.22"
          - tflint_version: "v0.58.1"
    env:
      ALPINE_VERSION: ${{ matrix.alpine_version }}
      TERRAFORM_VERSION: ${{ matrix.terraform_version }}
      TFLINT_VERSION: ${{ matrix.tflint_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Execute cibuild
        run: ./scripts/cibuild

      - name: Execute cipublish
        run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          CR_USER: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
