name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.3.4", "1.3.5"]
        include:
          - terragrunt_version: "v0.40.0"
            awscli_version: "2.9.0"
    env:
      DOCKER_BUILDKIT: 1
      TERRAFORM_VERSION: ${{ matrix.terraform_version }}
      TERRAGRUNT_VERSION: ${{ matrix.terragrunt_version }}
      AWSCLI_VERSION: ${{ matrix.awscli_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Execute cibuild
        run: ./scripts/cibuild

      - name: Execute cipublish
        run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          CR_USER: ${{ github.actor }}
          CR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
